version: "3"
services:
  back-end:
    build:
      dockerfile: Dockerfile
      context: .
    image: app
    container_name: app-cont
    depends_on:
      - database
    ports:
      - 8088:8088
    env_file:
      - spring.env
  # front-end:
  #   image: ui
  #   container_name: ui-cont
  #   ports:
  #     - 3131:3131
  #   environment:
  #     - REACT_APP_API_URL = "http://app-cont:8088"
  #   depends_on:
  #     - back-end
  database:
    image: mysql
    container_name: db-cont
    ports:
      - 3307:3306
    env_file:
      - database.env
    volumes:
      - my-vol:/var/lib/mysql
volumes:
  my-vol:
    external: true
